FROM node:20 AS build
WORKDIR /src
COPY apps/web-frontend/package*.json ./
RUN npm ci
COPY apps/web-frontend ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /src/dist /usr/share/nginx/html
COPY infra/docker/nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80